spring.application.name=mycoolapp

management.endpoints.web.exposure.include=*

management.info.env.enabled=true

info.app.name=Bhaskar app
info.app.description= Bhaskar Own app description
info.app.version =1.0.0

management.endpoints.web.exposure.exclude=health,info

coach.name=Bhaskar
team.name=Chennai super kings

